### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by steve-gray** [steve-gray/ebb#1]
Cleanup
- [ ] Write documentation/manual
- [ ] Create example projects

Formatters
- [ ] BSON Support

Transports
- [ ] Kafka Consumer Support (naieve)
- [ ] Memory / InProc Transport
